---
kind: pipeline
name: molecule

environment:
  MOLECULE_IMAGES: >
    debian-10

steps:
  - name: Lint
    image: veselahouba/molecule
    commands:
      - shellcheck_wrapper
      - flake8
      - yamllint .
      - ansible-lint

  - name: Molecule test
    image: veselahouba/molecule
    environment:
      HCLOUD_TOKEN:
        from_secret: HCLOUD_TOKEN
    commands:
      - ansible --version
      - molecule --version
      - REF=$$(echo $DRONE_COMMIT_REF | awk -F'/' '{print $$3}'|sed 's/_/-/g')
      - REPO_NAME=$$(echo $DRONE_REPO_NAME | sed 's/_/-/g')
      # Loop instead of matrix
      - |
        for MOLECULE_IMAGE in $${MOLECULE_IMAGES}; do
          export MOLECULE_IMAGE REPO_NAME REF
          molecule test --all
        done

---
kind: pipeline
name: release
depends_on:
  - molecule
trigger:
  event:
    - tag
steps:
  - name: Publish
    image: veselahouba/molecule
    environment:
      GALAXY_API_KEY:
        from_secret: GALAXY_API_KEY
    commands:
      - >
        ansible-galaxy role import --api-key $${GALAXY_API_KEY}
        $${DRONE_REPO_OWNER} $${DRONE_REPO_NAME}

  - name: Slack notification
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: ci-cd
      template: >
        {{#success build.status}}
          Publish for `{{build.tag}}` succeeded.
          {{build.link}}
        {{else}}
          Publish for `{{build.tag}}` failed.
          {{build.link}}
        {{/success}}
    when:
      status:
        - success
        - failure
