---
- name: Prepare dir for diskover
  file:
    path: "{{ diskover_persistent_path }}"
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Upload diskover config
  copy:
    src: "{{ item.filename }}"
    dest: "{{ diskover_persistent_path }}/{{ item.filename }}"
    owner: root
    group: root
    mode: "{{ item.mode|default('0644') }}"
  with_items:
    - filename: diskover.cfg
    - filename: diskover.key.pub
    - filename: "{{ diskover_ssh_key }}"
      mode: "0600"

- name: Upload docker compose
  template:
    src: docker-compose.yml.j2
    dest: "{{ diskover_persistent_path }}/docker-compose.yml"
    owner: root
    group: root
    mode: "0644"

- name: Apply elasticsearch requirements
  sysctl:
    name: vm.max_map_count
    value: "262144"

- name: Deploy docker compose
  include_role:
    name: veselahouba.docker_container
  vars:
    docker_composes: "{{ diskover_docker_composes }}"
